// // Drivers actions
// export const ADD_DRIVER = 'ADD_DRIVER';
// export const EDIT_DRIVER = 'EDIT_DRIVER';
// export const DELETE_DRIVER = 'DELETE_DRIVER';
// export const GET_DRIVER_LIST = 'GET_DRIVER_LIST';
// export const SYNC_DRIVERS = 'SYNC_DRIVER';
// // Administrators actions
// export const ADD_ADMINISTRATOR = 'ADD_ADMINISTRATOR';
// export const EDIT_ADMINISTRATOR = 'EDIT_ADMINISTRATOR';
// export const DELETE_ADMINISTRATOR = 'DELETE_ADMINISTRATOR';
// export const GET_AMDMINISTRATOR_LIST = 'GET_AMDMINISTRATOR_LIST';
// export const SYNC_ADMINISTRATOR = 'SYNC_ADMINISTRATOR';
// // vehicles actions
// export const ADD_VEHICLE = 'ADD_VEHICLE';
// export const EDIT_VEHICLE = 'EDIT_VEHICLE';
// export const DELETE_VEHICLE = 'DELETE_VEHICLE';
// export const SYNC_VEHICLE = 'SYNC_VEHICLE';

// Firebase auth user action
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';

export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
// export const EDIT_PARKING_USER = "EDIT_PARKING_USER"

export const MERGE_DRIVERS = 'MERGE_DRIVERS';
export const REMOVE_DRIVER_FROM_LIST = 'REMOVE_DRIVER_FROM_LIST';

export const REMOVE_ADMINISTRATOR_FROM_LIST = 'REMOVE_ADMINISTRATOR_FROM_LIST';
export const MERGE_ADMINISTRATORS = 'MERGE_ADMINISTRATORS';

export const REMOVE_VEHICLE_FROM_LIST = 'REMOVE_VEHICLE_FROM_LIST';
export const MERGE_VEHICLES = 'MERGE_VEHICLES';

export const REMOVE_GATE_FROM_LIST = 'REMOVE_GATE_FROM_LIST';
export const MERGE_LOCATION_GATES = 'MERGE_LOCATION_GATES';
export const MERGE_GATES = 'MERGE_GATES';

export const REMOVE_LOCATION_FROM_LIST = 'REMOVE_LOCATION_FROM_LIST';
export const MERGE_LOCATIONS = 'MERGE_LOCATIONS';
