export const ADD_PARKING_USER = 'ADD_PARKING_USER';
export const EDIT_PARKING_USER = 'EDIT_PARKING_USER';
export const DELETE_PARKING_USER = 'DELETE_PARKING_USER';
export const SET_PARKING_USER_LIST = 'SET_PARKING_USER_LIST';
export const SET_USER = 'SET_USER';
// export const EDIT_PARKING_USER = "EDIT_PARKING_USER"
