export const DRIVERS_ADD = 'DRIVERS_ADD';
export const DRIVERS_FETCH = 'DRIVERS_FETCH';
export const DRIVERS_FETCHALL = 'DRIVERS_FETCHALL';
export const DRIVERS_EDIT = 'DRIVERS_EDIT';
export const DRIVERS_DELETE = 'DRIVER_DELETE';

export const ADMINISTRATORS_ADD = 'ADMINISTRATORS_ADD';
export const ADMINISTRATORS_FETCH = 'ADMINISTRATORS_FETCH';
export const ADMINISTRATORS_FETCHALL = 'ADMINISTRATORS_FETCHALL';
export const ADMINISTRATORS_EDIT = 'ADMINISTRATORS_EDIT';
export const ADMINISTRATORS_DELETE = 'ADMINISTRATORS_DELETE';

export const VEHICLES_ADD = 'VEHICLES_ADD';
export const VEHICLES_FETCH = 'VEHICLES_FETCH';
export const VEHICLES_FETCHLIST = 'VEHICLES_FETCHLIST';
export const VEHICLES_FETCHALL = 'VEHICLES_FETCHALL';
export const VEHICLES_SYNC = 'VEHICLES_SYNC';
export const VEHICLES_EDIT = 'VEHICLES_EDIT';
export const VEHICLES_DELETE = 'VEHICLES_DELETE';

export const GATES_ADD = 'GATES_ADD';
export const GATES_FETCH = 'GATES_FETCH';
export const GATES_FETCHALL = 'GATES_FETCHALL';
export const GATES_EDIT = 'GATES_EDIT';
export const GATES_DELETE = 'GATES_DELETE';
export const GATES_UPDATE_LCD_MESSAGE = 'GATES_UPDATE_LCD_MESSAGE';

export const LOCATIONS_ADD = 'LOCATIONS_ADD';
export const LOCATIONS_FETCH = 'LOCATIONS_FETCH';
export const LOCATIONS_FETCHALL = 'LOCATIONS_FETCHALL';
export const LOCATIONS_EDIT = 'LOCATIONS_EDIT';
export const LOCATIONS_DELETE = 'LOCATIONS_DELETE';

export const EVENTS_FETCH = 'EVENTS_FETCH';
export const EVENTS_FETCHALL = 'EVENTS_FETCHALL';

export const HARDWARE_DATA_FETCH = 'HARDWARE_DATA_FETCH';
export const HARDWARE_DATA_FETCHALL = 'HARDWARE_DATA_FETCHALL';
export const AUTH = 'AUTH';
