export const DRIVERS_ADD = 'DRIVERS_ADD';
export const DRIVERS_FETCH = 'DRIVERS_FETCH';
export const DRIVERS_FETCHALL = 'DRIVERS_FETCHALL';
export const DRIVERS_EDIT = 'DRIVERS_EDIT';
export const DRIVERS_DELETE = 'DRIVER_DELETE';

export const ADMINISTRATORS_ADD = 'ADMINISTRATORS_ADD';
export const ADMINISTRATORS_FETCH = 'ADMINISTRATORS_FETCH';
export const ADMINISTRATORS_FETCHALL = 'ADMINISTRATORS_FETCHALL';
export const ADMINISTRATORS_EDIT = 'ADMINISTRATORS_EDIT';
export const ADMINISTRATORS_DELETE = 'ADMINISTRATORS_DELETE';

export const AUTH = 'AUTH';
export const VEHICLES = 'VEHICLES';
